name: "Automatically run benchmarks"
on:
  schedule:
  - cron: "0 0 * * *" # At the end of every day
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Install dependancy
        run: pip install matplotlib

      - name: Run benchmark script
        run: python readmeGen/generator.py
      - name: Run plot gen script
        run: python readmeGen/genGraph.py

      - name: Login
        run: git config --global user.name "actions-user" && git config --local user.email "actions@github.com" 

      - name: Commit changes
        run: git add . && git commit -am "Auto benchmark at $(date)"

      - name: Push changes
        run: git push
            